baseurl = "http://docs.pomoves.com/"
languageCode = "en-us"
title = "Pomoves Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-59834006-4"

[params]
	# General information
	author = "David Cruz"
	description = "Documentation and build process for Pomoves.com"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/pomoves/pm-docs"

	version = "0.0.1"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "pink"
    	accent  = "light green"

  [params.font]
  	text = "Roboto"
  	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "davidcv5"


[[menu.main]]
	name   = "What's Pomoves"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "User Guide"
	url    = "user-guide/"
	weight = 10

[[menu.main]]
	name   = "Developers"
	url    = "developers/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
